
server:
    port: 8082

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/hotphoto?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: admin
    security:
        user:
            name: zoey
            password: 123
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql